return {
    -- "zbirenbaum/copilot.lua",
    -- dependencies = {
    --     "copilotlsp-nvim/copilot-lsp", -- (optional) for NES functionality
    -- },
    -- config = function()
    --     require('copilot').setup({
    --         panel = {
    --             enabled = true,
    --             auto_refresh = true,
    --             keymap = {
    --                 jump_prev = "[[",
    --                 jump_next = "]]",
    --                 accept = "<CR>",
    --                 refresh = "gr",
    --                 open = "<M-CR>"
    --             },
    --             layout = {
    --                 position = "bottom",             -- | top | left | right | bottom |
    --                 ratio = 0.4
    --             }
    --         }
    --     });
    -- end
}
